[project]
name = 'healthcare-research-collaboration'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.clinical-trial-coordinator]
path = 'contracts/clinical-trial-coordinator.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-data-exchange]
path = 'contracts/research-data-exchange.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
